<SettingsScreen>
    FloatLayout:
        size_hint: 1, 0.05
		pos_hint: {"x": 0, 'y':0.95}
		ClockWidget:
		    text: "Clock Time"
		    id: clock
		    pos_hint: {"x": 0, 'y':0}
		ButtonImage:
		    text: "Settings"
		    size_hint: 0.03, 1
		    pos_hint: {"x": 0.97, 'y':0}
		    source: "../resources/Settings.png"


	GridLayout:
		id: menulayout
        size_hint: 1, 0.95
		pos_hint: {"x": 0, 'y':0}
		rows:2
		spacing: 20
		padding: 20
		Button:
			text: "Exit"
			on_release: app.stop()